### ISSUE TITLE
Add DPAD buttons for changing selection.

### ISSUE THREAD

**Issue by kn1meR** [DoktorSAS/H1Mapvote#10]
`self notifyonplayercommand("left", "+actionslot 3");`
`self notifyonplayercommand("right", "+actionslot 4");`

`if (command == "right" || command == "+speed_throw" || command == "+actionslot 4")`

`else if (command == "left" || command == "+attack" || command == "+actionslot 3")`

`else if (command == "select" || command == "+gostand" || command == "+usereload")`

Added these to my code last night and it worked as intended.  I suggest you add this for further ease of use with controller.

**Comment by DoktorSAS** [comment]
Solved <https://github.com/DoktorSAS/H1Mapvote/commit/9e1132ec9d55ea0db36f6463469ddecf5791aa12>
