### ISSUE TITLE
Missing mp_rundown

### ISSUE THREAD

**Issue by CarbonMac** [DoktorSAS/H1Mapvote#11]
I'm too lazy to make a pull request in the CLI rn. Many people likely don't even have `mp_rundown` due to a typo in the server config. This is currently missing in your name parser as well.

```
	case "mp_quarry":
		return "Quarry";
	case "mp_rundown":
		return "Rundown";
```

Also, I don't know shit about load screens, but I _think_,
```
	return "loadscreen_" + mapid;
```
should be

```
	return mapid + "_load";
```

**Comment by CarbonMac** [comment]
Also also, the MW2 list is not in the map pool.

```
SetDvarIfNotInizialized("mv_maps", "mp_convoy mp_backlot mp_bloc mp_bog mp_bog_summer mp_broadcast mp_carentan mp_countdown mp_crash mp_crash_snow mp_creek mp_crossfire mp_citystreets mp_farm mp_farm_spring mp_killhouse mp_overgrown mp_pipeline mp_shipment mp_showdown mp_strike mp_vacant mp_cargoship mp_afghan mp_complex mp_abandon mp_derail mp_estate mp_favela mp_fuel2 mp_highrise mp_invasion mp_checkpoint mp_quarry mp_rundown mp_rust mp_compact mp_boneyard mp_nightshift mp_storm mp_subbase mp_terminal mp_trailerpark mp_underpass mp_brecourt");
```

**Comment by dellmas** [comment]
Considering I've been running servers for months with the loadscreens in the mapvote, I'd say its good as is.

**Comment by CarbonMac** [comment]
As you see in the main screenshot in the readme, the loadscreens don't seem to load. At least for me on H2M. The code is even commented out to render it.

**Comment by dellmas** [comment]
It has to be modded to work, but works.

![image](https://github.com/user-attachments/assets/9f726ca8-357e-4fa5-949d-1494f51db5ec)

**Comment by dellmas** [comment]
![image](https://github.com/user-attachments/assets/9390b980-faa4-4f04-813c-dbdbf5e653d9)
![image](https://github.com/user-attachments/assets/b9e3a24d-717f-489b-9f3a-fc4677968e68)

I precached every which way I could think of. You can load calling cards in the mapvote boxes without modding but the map images wont.

**Comment by CarbonMac** [comment]
I will look up how to start breaking apart ff files I suppose :P should know this by know. Any advice? And I assume you mean I just shouldn't run the precache commands? I was thinking of trying to figure out a "pretty" 3x2 vote screen

**Comment by dellmas** [comment]
You can dump the ff with zonetool.

**Comment by dellmas** [comment]
![image](https://github.com/user-attachments/assets/efb5e511-d9bb-4972-be1a-51e2f7945fdf)

Annoys me how calling cards load up easy but map images wont.

**Comment by CarbonMac** [comment]
I’ll keep an eye on your first issue. Sry for wasting time
