### ISSUE TITLE
Map Repeats on the Mapvote

### ISSUE THREAD

**Issue by KasDev573** [DoktorSAS/H1Mapvote#2]
When I finish a game and the map vote appears, I often get one named map invalid. This has always been the map I just played. This itself is not an issue, however I do have two issues appearing.

One, I can have map invalid appear 2-3 times taking all the votes, something I would prefer to avoid.

Two, I can have map invalid appear 1-2 times alongside the vote for the map we just played with the proper name.

Is there any way to solve this issue? 

As a side note, every map name is followed by invalid when I have a vote.

![map vote issue](https://github.com/user-attachments/assets/81ba0e66-1109-4834-89ae-86442ddbdc15)

**Comment by KasDev573** [comment]
It also appears far more often/takes 2-3 slots far more often than having a different map (different from the one I just played) to appear.

**Comment by DoktorSAS** [comment]
Thanks for the report, could you please provide the dvars value (inside the cfg)? It seems that are not set correctly and it choose an invalid maps from the list.

**Comment by KasDev573** [comment]
Sorry for taking so long to get back to you. I deleted the .cfg contents that it mentioned to add to the .cfg file and simply left the mapvote script in the script folder and now everything appears to be working. No more "invalid" and the repeats are incredibly rare as in the past 5 days I only experienced it once where the same map was listed 2x.
