### ISSUE TITLE
[H2M] Single gamemode issue/feature request

### ISSUE THREAD

**Issue by mrdynamo** [DoktorSAS/H1Mapvote#5]
I am running a couple servers with single game mode, but I want users to be able to vote for maps.

When enabling map vote, the game modes are random. I put just a single game mode in the gametypes dvar, but they are still random modes.

Is this not working properly? Or am I missing something

**Comment by dellmas** [comment]
What do you have here and here?

set sv_mapRotation "gametype war map mp_convoy map mp_backlot map mp_bog map mp_crash map mp_crossfire map mp_citystreets map mp_farm map mp_overgrown map mp_shipment map mp_vacant map mp_broadcast map mp_carentan map mp_countdown map mp_bloc map mp_creek map mp_killhouse map mp_pipeline map mp_strike map mp_showdown map mp_cargoship map mp_crash_snow map mp_farm_spring map mp_bog_summer"


set mv_gametypes        "war;"

**Comment by MrDynamo** [comment]
`set sv_maprotation "gametype dom map mp_afghan map mp_complex map mp_abandon map mp_derail map mp_estate map mp_favela map mp_fuel2 map mp_highrise map mp_invasion map mp_checkpoint map mp_quarry map mp_rundown map mp_rust map mp_compact map mp_boneyard map mp_nightshift map mp_storm map mp_subbase map mp_terminal map mp_trailerpark map mp_underpass map mp_brecourt"`

`set mv_gametypes          "dom"`

**Comment by mrdynamo** [comment]
> What do you have here and here?
> 
> set sv_mapRotation "gametype war map mp_convoy map mp_backlot map mp_bog map mp_crash map mp_crossfire map mp_citystreets map mp_farm map mp_overgrown map mp_shipment map mp_vacant map mp_broadcast map mp_carentan map mp_countdown map mp_bloc map mp_creek map mp_killhouse map mp_pipeline map mp_strike map mp_showdown map mp_cargoship map mp_crash_snow map mp_farm_spring map mp_bog_summer"
> 
> set mv_gametypes "war;"

`set sv_maprotation "gametype dom map mp_afghan map mp_complex map mp_abandon map mp_derail map mp_estate map mp_favela map mp_fuel2 map mp_highrise map mp_invasion map mp_checkpoint map mp_quarry map mp_rundown map mp_rust map mp_compact map mp_boneyard map mp_nightshift map mp_storm map mp_subbase map mp_terminal map mp_trailerpark map mp_underpass map mp_brecourt"`

`set mv_gametypes          "dom"`

**Comment by dellmas** [comment]
Possibly some issue with the h2m addon. The Dok is likely asleep rn.

For giggles try adding a ;

set mv_gametypes          "dom;"

**Comment by DoktorSAS** [comment]
@MrDynamo 
Its correct to set mv_gametypes to just dom but you have mv_gametypes_norepeat set to 1 and this mean that you have only one options. 
If you just want one gamemode you can do:
1. Keep one gametypes on mv_gametypes and set mv_gametypes_norepeat to 0.
2. Set mv_gametypes to "dom dom dom" and keep mv_gametypes_norepeat to whotever value it is.

sv_maprotation make no difference to how the mapvote behave. sv_maprotation must be set to at least run the server with a gametype and a map (this first one).

**Comment by MrDynamo** [comment]
setting `set mv_gametypes_norepeat 0` does indeed fix the issue and it is all one gametype as defined by `set mv_gametypes          "sd"`. 

I think my confusion came from the comment on the gametypes_norepeat field. Currently it is `// If set to 0 all options will have a different gametype`, which reads like if it set to '0', the gametypes will rotate. I think this should read `// If set to 1, all options will have a different gametype`.

**Comment by mrdynamo** [comment]
> @MrDynamo Its correct to set mv_gametypes to just dom but you have mv_gametypes_norepeat set to 1 and this mean that you have only one options. If you just want one gamemode you can do:
> 
>     1. Keep one gametypes on mv_gametypes and set mv_gametypes_norepeat to 0.
> 
>     2. Set mv_gametypes to "dom dom dom" and keep mv_gametypes_norepeat to whotever value it is.
> 
> 
> sv_maprotation make no difference to how the mapvote behave. sv_maprotation must be set to at least run the server with a gametype and a map (this first one).

setting `set mv_gametypes_norepeat 0` does indeed fix the issue and it is all one gametype as defined by `set mv_gametypes "sd"`. 

I think my confusion came from the comment on the gametypes_norepeat field. Currently it is `// If set to 0 all options will have a different gametype`, which reads like if it set to '0', the gametypes will rotate. I think this should read `// If set to 1, all options will have a different gametype`.
