### ISSUE TITLE
First come first serve

### ISSUE THREAD

**Issue by dellmas** [DoktorSAS/H1Mapvote#6]
As it stands you have:

firstmap secondmap thirdmap for your mapvote.

If you vote for secondmap and just before timer ends someone else votes firstmap, it's going to pick firstmap. Basically if all maps have 1 vote its going to go firstmap.

Can you edit the code to go with the first vote cast unless 2 or more votes are present on another map?

**Comment by DoktorSAS** [comment]
Solved in https://github.com/DoktorSAS/H1Mapvote/commit/92593f4f0ca65e4d76cbb73da7c19a08837741fc 
Thanks for reporting the issue
