### ISSUE TITLE
Invalid gamemodes with mv_extended

### ISSUE THREAD

**Issue by Valacdi** [DoktorSAS/H1Mapvote#9]
Invalid gamemodes shown when the user has set less than 6 (or 5 if random is on) gamemodes on the DVAR mv_gametypes

for example mv_gametypes is set on "conf dom war"

the 4th, 5th and 6th choices will show invalid gamemode

**Comment by Lucidic15** [comment]
was there an issue here? what did you find out?

**Comment by Valacdi** [comment]
> was there an issue here? what did you find out?

you fixed it after I posted this issue, the commit b5a9e26 fixed it
